import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { ArticleComponent } from './article/article.component'; //import new by handmade ArticleComponent in case not generated by command line

@NgModule({
  declarations: [
    AppComponent,
    ArticleComponent  // In order to tell our AppComponent about our newly created "by hand" ArticleComponent component, we need to add the ArticleComponont to the list of declarations in this NgModule.
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
